name: Build page and push to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build site
      uses: addnab/docker-run-action@v3
      with:
        image: squidfunk/mkdocs-material:latest
        options: -v /home/runner/work/support/support:/docs
        run: mkdocs build -f config/en/mkdocs.yml && mkdocs build -f config/es/mkdocs.yml
      
    - name: Copy CNAME
      run: cp CNAME dist/CNAME
        
    - name: Push to branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"
